#include <stdint.h>


#define MAX_FILES 255
typedef uint8_t FILE_COUNT_T;

typedef void assemble_opt_t;

typedef struct {
  char* ptr;
  size_t size;
} strview_t;

typedef struct {
  union {
    char TOKEN_LITERAL_CHAR;
    uint8_t TOKEN_STR_DELIMITERS_SIZE;
    uint8_t TOKEN_LITERAL_U8;
    uint16_t TOKEN_LITERAL_U16;
    uint32_t TOKEN_LIRERAL_U32;
    uint64_t TOKEN_LIRERAL_U64;
    size_t TOKEN_LIRERAL_USIZE;
    int8_t TOKEN_LITERAL_I8;
    int16_t TOKEN_LITERAL_I16;
    int32_t TOKEN_LIRERAL_I32;
    int64_t TOKEN_LIRERAL_I64;
    ptrdiff_t TOKEN_LIRERAL_ISIZE;
    float TOKEN_LITERAL_FLOAT;
    double TOKEN_LITERAL_DOUBLE;
    bool TOKEN_DELIMITER_CLOSING;
  } value;
  size_t byte_pos;
  size_t size;
  FILE_COUNT_T file_id;
  enum {
    TOKEN_IDENTIFIER,
    TOKEN_LITERAL_CHAR,
    TOKEN_LITERAL_STR,
    TOKEN_LITERAL_U8,
    TOKEN_LITERAL_U16,
    TOKEN_LIRERAL_U32,
    TOKEN_LIRERAL_U64,
    TOKEN_LIRERAL_USIZE,
    TOKEN_LITERAL_I8,
    TOKEN_LITERAL_I16,
    TOKEN_LIRERAL_I32,
    TOKEN_LIRERAL_I64,
    TOKEN_LIRERAL_ISIZE,
    TOKEN_LITERAL_FLOAT,
    TOKEN_LITERAL_DOUBLE,
    TOKEN_KEYWORD_INCLUDE,
    TOKEN_KEYWORD_CONST,
    TOKEN_KEYWORD_FN,
    TOKEN_KEYWORD_RETURN,
    TOKEN_KEYWORD_IF,
    TOKEN_KEYWORD_ELSE,
    TOKEN_DELIMITER_PARENTHESIS,
    TOKEN_DELIMITER_BRACE,
    TOKEN_DELIMITER_BRACKET,
    TOKEN_DELIMITER_COMMA,
    TOKEN_DELIMITER_SEMICOLON,
    TOKEN_OPERATOR_EQUAL
  } type;
} token_t;

strview_t open_file(char*);
size_t tokenize_file(strview_t, da_t*, FILE_COUNT_T);

typedef enum {
  COMMENT_NONE,
  COMMENT_MAYBE,
  COMMENT_YES
} comment_e;

typedef enum {
  PARSING_NONE,
  PARSING_CHAR,
  PARSING_STRING,
  PARSING_NUMBER,
  PARSING_FLOAT,
  PARSING_IDENTIFIER
} parsing_e;

